package com.example.grupo22_kotlin.presentation.screens.signup.components

class Careers {
    val careers: List<String> = listOf(
        "Administración",
        "Antropología",
        "Arquitectura",
        "Arte",
        "Biología",
        "Ciencia política",
        "Derecho",
        "Diseño",
        "Economía",
        "Estudios generales",
        "Filosofía",
        "Física",
        "Geociencias",
        "Gobierno y asuntos públicos",
        "Historia",
        "Historia del arte",
        "Ingeniería ambiental",
        "Ingeniería Biomédica",
        "Ingeniería civil",
        "Ingeniería de alimentos",
        "Ingeniería de sistemas y computación",
        "Ingeniería electrica",
        "Ingeniería electrónica",
        "Ingeniería industrial",
        "Ingeniería mecánica",
        "Ingeniería química",
        "Lenguas y cultura",
        "Licenciatura en artes",
        "Licenciatura en biología",
        "Licenciatura en educación infantil",
        "Licenciatura en español y filología",
        "Licenciatura en filosofía",
        "Licenciatura en física",
        "Licenciatura en matemática",
        "Licenciatura en química",
        "Literatura",
        "Matemáticas",
        "Medicina",
        "Microbiología",
        "Música",
        "Narrativas digitales",
        "Psicología",
        "Química"
    )
}